config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

 

  devise_for :users
  
  resources :pharms do
    resources :gardes
  end
  resources :towns

  namespace :api do
    namespace :v1 do
      resources:pharms
      resources:gardes
    end  
  end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garde.rb
class Garde < ApplicationRecord
  belongs_to :pharm
end

app/models/pharm.rb
class Pharm < ApplicationRecord
    validates :commune, presence:true
    validates :pharma_name, presence:true
    validates :owner_name, presence:true
    validates :description, presence:true
    validates :tel, presence:true
    validates :h_openning, presence:true
    validates :h_closing, presence:true
    validates :description, presence:true
    belongs_to :user
    has_many :gardes

    scope :search, -> (search) { where pharms: search }
end

app/models/town.rb
class Town < ApplicationRecord
    validates :name, presence:true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :firt_name, presence:true
  validates :last_name, presence:true

  has_many :pharms
end

app/controllers/api/v1/gardes_controller.rb
class Api::V1::GardesController < ApplicationController
    before_action :set_garde, :set_pharm,  except: [:index, :show]
    def index
        if params[:search]
            @gardes = Garde.includes(:pharm).all
        else
            @gardes = Garde.includes(:pharm).all
        end
    end

    def show
    end
    
    private

        def set_pharm
            @garde = Garde.find(params[:id])
        end

        def set_pharm
            @pharm = Pharm.find(params[:id])
        end
end

app/controllers/api/v1/pharms_controller.rb
class Api::V1::PharmsController < ApplicationController
    before_action :set_pharm, except: [:index]
    def index
        if params[:search]
            @pharms = Pharm.all.where(commune:params[:search]).where(garde:true)
        else
            @pharms = Pharm.all.where(garde:true)
        end
    end

    def show
    end
    
    private
        def set_pharm
            @pharm = Pharm.find(params[:id])
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) do |user_params|
        user_params.permit(:firt_name, :last_name, :email, :password, :password_confirmation, :remember_me)
      end
      devise_parameter_sanitizer.permit(:sign_in) do |user_params|
        user_params.permit(:email, :password, :remember_me)
      end
      devise_parameter_sanitizer.permit(:account_update) do |user_params|
        user_params.permit(:firt_name, :last_name, :email, :password, :current_password)
      end
    end
end

app/controllers/gardes_controller.rb
class GardesController < ApplicationController
     before_action :authenticate_user!, :set_garde, only: [:show, :edit, :update, :destroy]
    
    def index
        @gardes = Garde.includes(:pharm).all.where(garde:true).all
    end

    def show 
          
    end

    def new
        @garde = Garde.new
    end

    def edit  
    end

   

    def create
        @pharm = Pharm.find(params[:pharm_id])
        @garde = @pharm.gardes.new(garde_params)
        if @garde.save
            redirect_to @pharm, notice: 'Garde was successfully created.' 
        else
            render :new 
        end
    end

    def update
        @pharm = Pharm.find(params[:pharm_id])
        if @garde.update(town_params)
            redirect_to @pharm, notice: 'Garde was successfully edited.' 
        else
            render :edit 
        end
    end

    def destroy
        @town.destroy redirect_to pharms_url, notice: 'Garde was successfully destroyed.' 
    end

    private
        def set_garde
            @garde = Garde.find(params[:id])
        end

        def garde_params
            params.require(:garde).permit(:garde, :star_date, :end_date, :pharm_id)
        end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    before_action :authenticate_user!

    def index
        
    end
end

app/controllers/pharms_controller.rb
class PharmsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show, :edit, :new, :update, :destroy]

  # GET /pharms
  # GET /pharms.json
  def index
    if params[:search]
      @pharms = Pharm.all.search(commune:params[:search]).where(garde:true)
    else
      @pharms = Pharm.where(garde:true).all
    end
  end

  # GET /pharms/1
  # GET /pharms/1.json
  def show
    @pharm = Pharm.find(params[:id])
  end

  # GET /pharms/new
  def new

    @pharm = Pharm.new
  end

  # GET /pharms/1/edit
  def edit
    @pharm = Pharm.find(params[:id])
  end

  # POST /pharms
  # POST /pharms.json
  def create
    @pharm = Pharm.new(pharm_params)
    @pharm.user_id = current_user.id

    respond_to do |format|
      if @pharm.save
        format.html { redirect_to @pharm, notice: 'Pharm was successfully created.' }
        format.json { render :show, status: :created, location: @pharm }
      else
        format.html { render :new }
        format.json { render json: @pharm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pharms/1
  # PATCH/PUT /pharms/1.json
  def update
    @pharm = Pharm.find(params[:id])
    respond_to do |format|
      if @pharm.update(pharm_params)
        format.html { redirect_to @pharm, notice: 'Pharm was successfully updated.' }
        format.json { render :show, status: :ok, location: @pharm }
      else
        format.html { render :edit }
        format.json { render json: @pharm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pharms/1
  # DELETE /pharms/1.json
  def destroy
    @pharm = Pharm.find(params[:id])
    @pharm.destroy
    respond_to do |format|
      format.html { redirect_to pharms_url, notice: 'Pharm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pharm
      @pharm = Pharm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pharm_params
      params.require(:pharm).permit(:commune, :pharma_name, :owner_name, :description, :tel, :lat, :long, :h_openning, :h_closing, :garde, :star_date, :end_date)
    end
end

app/controllers/towns_controller.rb
class TownsController < ApplicationController
    before_action :authenticate_user!, :set_town, only: [:show, :edit, :update, :destroy]
    
    def index
        @towns = Town.all   
    end

    def show 
          
    end

    def new
        @town = Town.new
    end

    def edit  
    end

   

    def create
        @town = Town.new(town_params)
        if @town.save
            redirect_to @town, notice: 'Town was successfully created.' 
        else
            render :new 
        end
    end

    def update
        if @town.update(town_params)
            redirect_to @town, notice: 'Town was successfully edited.' 
        else
            render :edit 
        end
    end

    def destroy
        @town.destroy redirect_to pharms_url, notice: 'Town was successfully destroyed.' 
    end

    private
        def set_town
            @town = Town.find(params[:id])
        end

        def town_params
            params.require(:town).permit(:name)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardes_helper.rb
module GardesHelper
end

app/helpers/pharms_helper.rb
module PharmsHelper
end

app/views/gardes/_form.html.erb
<%= simple_form_for [@pharm, @pharm.gardes.new] do |f| %>
  <%= f.input_field :garde, as: :boolean, boolean_style: :inline %>
  <%= f.input :star_date %>
  <%= f.input :end_date %>
  
  <%= f.button :submit %>
<% end %>

app/views/gardes/index.html.erb
<h1>Gardes</h1>

<% @gardes.each do |garde| %>
  <%= garde.pharm.commune%> <br>
<% end %>

app/views/home/index.html.erb
<h1>Bienvenue sur l'APP</h1>

<%= link_to 'Voir la liste des Pharmacies', pharms_path, class:'btn btn-secondary'  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pharmacie</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  </head>

  <body>

  <div class="header">

    <div class="header-container">
        <nav>
          <ul class="nav nav-pills float-right">
            
            <li class="nav-item">
            <% if !user_signed_in? %>

              <%= link_to 'Connexion', new_user_session_path, class:'nav-link'%>

            <% else %>
    
              <%= link_to 'Deconnexion', destroy_user_session_path, method: :delete , class:'nav-link'%> 
            <%end%>
            </li>
           
          </ul>
        </nav>
        
        <h3 class="h-text-muted">Pharm'App</h3>
      </div>

    </div>
    <div class="container">
 
        

       

      <div >
  
            <% if notice %>
 
              <div id="notice_wrapper" class="alert alert-success fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
                <strong><%= notice %></strong>
              </div>



            <% end %>

            <% if alert %>
 
              <div id="notice_wrapper" class="alert alert-danger fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
                <strong><%= alert %></strong>
              </div>


              
            <% end %>

      </div>

      <% if user_signed_in? %>
        
        <%= link_to 'Ajouter une pharmacie', new_pharm_path, class:'btn btn-success'%>

      <%end%>

      <%= yield %>
    </div>  

    <script>
        $(document).ready(function(){
          setTimeout(function(){
            $('#notice_wrapper').fadeOut("slow", function(){
              $(this).remove();
            })
          }, 5000)
        })
    </script>
  </body>

  </html>

app/views/pharms/_form.html.erb
<%= form_for(pharm) do |f| %>
  <% if pharm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pharm.errors.count, "error") %> prohibited this pharm from being saved:</h2>
      <ul>
      <% pharm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :Commune %> 
  
    
<%= f.select(:commune)do %>
    <%= options_for_select(
    [
      ['Abengourou', 'abengourou'], ['Abobo', 'abobo' ],['Abobodoume','abobodoume'],['Aboisso','aboisso'],['Adjame','adjame'],['Agboville','agboville'],['Agnibilekro','agnibilekro'],['Anyama','anyama'],['Attecoube','attecoube'],
      ['Bingerville','bingerville'],['Bondoukou','bondoukou'],['Bouafle','bouafle'],['Bouake','bouake'],['Cocody','cocody'],['Dabou','dabou'],['Daloa','daloa'],['Dimbokro','dimbokro'],['Divo','divo'],['Duekoue','duekoue'],['Ferkessedougou','ferkessedougou'],
      ['Gagnoa','gagnoa'],['Grand-Bassam','grand bassam'],['Guiglo','guiglo'],['2 Plateau','2 plateau'],['Issia','issia'],['Koumassi','koumassi'],['Man','man'],['Marcory','marcory'],['Odienne','odienne'],['Plateau','plateau'],['Port Bouet','port bouet'],
      ['Vridi','vridi'],['Riviera','riviera'],['San Pedro','san pedro'],['Soubre','soubre'],['Toumoditoumodi','toumodi'],['Treichville','treichville'],['Williamsville','williamsville'],['Yamoussoukro','yamoussoukro'],['Yopougon','yopougon']
    ], @pharm.commune
    )%>
<%end%>
  </div>

  <div class="form-group">
    <%= f.label :Nom_de_la_pharmacie %> 
    <%= f.text_field :pharma_name, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :Nom_du_pharmacien %> 
    <%= f.text_field :owner_name, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %> 
    <%= f.text_area :description, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :tel %> 
    <%= f.text_field :tel, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :lat %> 
    <%= f.text_field :lat, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :long %> 
    <%= f.text_field :long, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :h_openning %> 
    <%= f.time_field :h_openning, class:'form-control', value:'08:00' %>
  </div>

  <div class="form-group">
    <%= f.label :h_closing %> 
    <%= f.time_field :h_closing, class:'form-control', value:'20:00' %>
  </div>

  <div class="form-group">
    <%= f.label :Debut_garde %> 
    <%= f.date_field :star_date, class:'form-control'%>
  </div>


  <div class="form-group">
    <%= f.label :Fin_garde %> 
    <%= f.date_field :end_date, class:'form-control'%>
  </div>

<div class="form-group">
  <%= f.label :garde, 'Garde' %>
   <%= f.radio_button :garde, true, :value => true%>
   <%= f.radio_button :garde, false, :value => false%>
</div>
  <div class="form-group">
    <%= f.submit class:'btn btn-success' %>
  </div>
<% end %>

app/views/pharms/edit.html.erb
<h1>Editing Pharm</h1>

<%= render 'form', pharm: @pharm %>

<%= link_to 'Show', @pharm %> |
<%= link_to 'Back', pharms_path %>

app/views/pharms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Toutes les pharmacies</h1>

<table class="table table-striped">
  
    <% @pharms.each do |pharm| %>
      <tr>
        <td><%= pharm.commune.capitalize %></td>
        <td><%= pharm.pharma_name %></td>
        <td>
             
            <%= link_to 'Edit', edit_pharm_path(pharm), class:'btn btn-outline-primary' %>
          
        </td>
 
      </tr>

      
      
    <% end %>
 
</table>
 

app/views/pharms/new.html.erb
<h1>New Pharm</h1>

<%= render 'form', pharm: @pharm %>

<%= link_to 'Back', pharms_path %>

app/views/pharms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
 
  <%= @pharm.commune %>
</p>

<p>
  <%= @pharm.pharma_name %>
</p>

<p>
 
  <%= @pharm.owner_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pharm.description %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @pharm.tel %>
</p>
<p>
  <strong>Lat:</strong>
  <%= @pharm.lat %>
</p>

<p>
  <strong>Long:</strong>
  <%= @pharm.long %>
</p>

<p>
  <strong>H openning:</strong>
  <%= @pharm.h_openning %>
</p>

<p>
  <strong>H closing:</strong>
  <%= @pharm.h_closing %>
</p>

<%= render 'gardes/form'%>

<%= link_to 'Edit', edit_pharm_path(@pharm) %> |
<%= link_to 'Back', pharms_path %>

app/views/towns/_form_town.html.erb
<%= simple_form_for @town do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/towns/edit.html.erb
<h1>Editing Pharm</h1>

<%= render 'form_town', town: @town %>

<%= link_to 'Show', @town %> |
<%= link_to 'Back', towns_path %>

app/views/towns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Toutes les townacies</h1>

<%= link_to 'Ajouter une townacie', new_town_path, class:'btn btn-success'%>

<table class="table">
  
    <% @towns.each do |town| %>
      <tr>
        <td><%= town.name %></td>
        <td>
            <%= link_to 'Show', town, class:'btn btn-secondary' %>
            <%= link_to 'Edit', edit_town_path(town), class:'btn btn-primary' %>
            <%= link_to 'Destroy', town, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-warning' %>
      </td>
 
      </tr>

      
      
    <% end %>
 
</table>
 

app/views/towns/new.html.erb
<h1>New town</h1>

<%= render 'form_town' %>

<%= link_to 'Back', towns_path %>

app/views/towns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
 
  <%= @town.name %>
</p>
 
<%= link_to 'Edit', edit_town_path(@town) %> |
<%= link_to 'Back', towns_path %>